# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cataract.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CataractDetection(object):
    def setupUi(self, CataractDetection):
        CataractDetection.setObjectName("CataractDetection")
        CataractDetection.resize(698, 623)
        self.pushButton = QtWidgets.QPushButton(CataractDetection)
        self.pushButton.setGeometry(QtCore.QRect(60, 210, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(CataractDetection)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 170, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.graphicsView = QtWidgets.QGraphicsView(CataractDetection)
        self.graphicsView.setGeometry(QtCore.QRect(190, 140, 281, 231))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(CataractDetection)
        self.label.setGeometry(QtCore.QRect(190, 390, 141, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CataractDetection)
        self.label_2.setGeometry(QtCore.QRect(350, 390, 121, 21))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CataractDetection)
        self.label_3.setGeometry(QtCore.QRect(190, 420, 141, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(CataractDetection)
        self.label_4.setGeometry(QtCore.QRect(350, 420, 121, 21))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(CataractDetection)
        self.label_5.setGeometry(QtCore.QRect(160, 80, 361, 51))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(CataractDetection)
        QtCore.QMetaObject.connectSlotsByName(CataractDetection)

    def retranslateUi(self, CataractDetection):
        _translate = QtCore.QCoreApplication.translate
        CataractDetection.setWindowTitle(_translate("CataractDetection", "Form"))
        self.pushButton.setText(_translate("CataractDetection", "Check"))
        self.pushButton_2.setText(_translate("CataractDetection", "Choose"))
        self.label.setText(_translate("CataractDetection", "Prediction Confidence :"))
        self.label_3.setText(_translate("CataractDetection", "Type :"))
        self.label_5.setText(_translate("CataractDetection", "                              Cataract Detection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CataractDetection = QtWidgets.QWidget()
    ui = Ui_CataractDetection()
    ui.setupUi(CataractDetection)
    CataractDetection.show()
    sys.exit(app.exec_())
